In [26]:
import numpy as np
#example grid where blank cells are valued 0
grid = [[0, 0, 3, 0, 2, 9, 0, 0, 1], 
        [6, 0, 0, 1, 0, 0, 4, 0, 0],
        [0, 0, 8, 3, 7, 0, 0, 0, 0],
        [9, 0, 4, 0, 0, 0, 0, 0, 0],
        [0, 6, 1, 0, 0, 0, 0, 5, 8],
        [0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 5, 0, 0, 0, 0, 0, 6, 0],
        [0, 0, 0, 8, 6, 0, 0, 4, 0],
        [7, 0, 0, 0, 0, 0, 0, 0, 0]]
#to see the grid in a ordered way
#print(np.matrix(grid))
def possiblity(x, y, n):
    #declaring grid as global 
    global grid
    for i in range(9):
        if (grid[i][y] == n):
            return False
    for i in range(9):
        if (grid[x][i] == n):
            return False
    x0 = (x // 3) * 3
    y0 = (y // 3) * 3
    for i in range(3):
        for j in range(3):
            if (grid[x0 + i][y0 + j] == n):
                return False
    return True
def solver():
    global grid
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                for l in range(1, 10):
                    if possiblity(i, j, l):
                        #if possiblity for a number is true then assign the value
                        grid[i][j] = l
                        #using recursion for sailing through every possiblities
                        solver()
                        #if no solution found again assign to 0
                        grid[i][j] = 0
                return 
    print(np.matrix(grid))
solver()
        

[[0 0 3 0 2 9 0 0 1]
 [6 0 0 1 0 0 4 0 0]
 [0 0 8 3 7 0 0 0 0]
 [9 0 4 0 0 0 0 0 0]
 [0 6 1 0 0 0 0 5 8]
 [0 0 0 0 0 2 0 0 0]
 [0 5 0 0 0 0 0 6 0]
 [0 0 0 8 6 0 0 4 0]
 [7 0 0 0 0 0 0 0 0]]
[[5 4 3 6 2 9 7 8 1]
 [6 2 7 1 5 8 4 3 9]
 [1 9 8 3 7 4 5 2 6]
 [9 7 4 5 8 6 3 1 2]
 [2 6 1 4 3 7 9 5 8]
 [8 3 5 9 1 2 6 7 4]
 [4 5 2 7 9 1 8 6 3]
 [3 1 9 8 6 5 2 4 7]
 [7 8 6 2 4 3 1 9 5]]
